### ISSUE TITLE
Size of No-Hair FFHQ

### ISSUE THREAD

**Issue by MrTornado24** [oneThousand1000/non-hair-FFHQ#6]
Hi, interesting work and I love it. I downloaded the dataset from the google drive link, however, I found only about 15000 no-hair images. Is there something wrong with downloading or the dataset itself is incomplete?

**Comment by oneThousand1000** [comment]
> Hi, interesting work and I love it. I downloaded the dataset from the google drive link, however, I found only about 15000 no-hair images. Is there something wrong with downloading or the dataset itself is incomplete?

Hi!

I just checked the number of images in the two folders and I found no issue here. There are 6,000 non-hair images in `non-hair` and 6,000 hair images in `hair`.

By the way, did you check all the files that are downloaded from the google drive link? (The google drive will split the .rar/.zip file into several files with smaller sizes)
![捕获](https://user-images.githubusercontent.com/32099648/182097215-d77f9200-a788-435c-9b62-2a6e9805d0dd.PNG)

**Comment by MrTornado24** [comment]
Thanks for your quick reply! I have just noticed that the indexes are not continuous, so I have downloaded all the images. I wonder why there are 6000 no-hair images considering the whole size of ffhq is 70000.

**Comment by oneThousand1000** [comment]
> Thanks for your quick reply! I have just noticed that the indexes are not continuous, so I have downloaded all the images. I wonder why there are 6000 no-hair images considering the whole size of ffhq is 70000.

We only processed 6,000 portraits in FFHQ (We also noted it in the description). Because our method doesn't work well for all images in FFHQ (due to extreme lighting conditions, occlusions, and so on) and we manually select some ideal results.

**Comment by MrTornado24** [comment]
Thanks so much, I got it.
