### ISSUE TITLE
Empty images in non-hair-FFHQ dataset

### ISSUE THREAD

**Issue by Gojay001** [oneThousand1000/non-hair-FFHQ#7]
Hi, thanks for your excellent work.
I found some empty images in the dataset that you support, 
that is, [non-hair-FFHQ/hair/**14563.png**], [non-hair-FFHQ/hair/**14598.png**].

**Comment by oneThousand1000** [comment]
Have updated. Thanks!

14563: https://drive.google.com/file/d/1B113g_qTMam2NGo8nzE5L42SZ_NqvKwd/view?usp=sharing
14598: https://drive.google.com/file/d/1BOz3pqQUZK7RfSzELgzECT-NPHR1lGRi/view?usp=sharing
